### ISSUE TITLE
Support reading / writing extra-deps 

### ISSUE THREAD

**Issue by tmcgilchrist** [erikd/jenga#2]
stack.yaml has a section for libraries not found in stackage or whose version is different from that in stackage. It would be helpful if jenga supported reading that and writing it to the `cabal.config` file.

eg
```yaml
# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- SHA2-0.2.5
```

Happy to look into adding this myself.

**Comment by erikd** [comment]
Probably need to first un-savage the way i'm reading the resolver version from the `stack.yaml` file. If we're pulling anything other than the resolver version from that file we should use the proper yaml parser.

**Comment by erikd** [comment]
More info about `extra-deps` in [this reddit comment](https://www.reddit.com/r/haskell/comments/5xm5ha/jenga_new_tool_to_generate_cabal_freeze_file_from/del5r67/).

**Comment by erikd** [comment]
The first step, using Data.Yaml to parse the stack.yaml file is now on master.
